// <auto-generated />
using System;
using AgentHub.Orchestration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentHub.Orchestration.Migrations
{
    [DbContext(typeof(AgentHubDbContext))]
    [Migration("20260310095448_AddWorktreeColumns")]
    partial class AddWorktreeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.ApprovalEntity", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeoutAction")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApprovalId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.HostEntity", b =>
                {
                    b.Property<string>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowSsh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MemTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MemUsedMb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("MetricsUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HostId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupState")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFireAndForget")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepBranch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Node")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskAcceptedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreeBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ParentSessionId");

                    b.HasIndex("State");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.SessionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TsUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.ApprovalEntity", b =>
                {
                    b.HasOne("AgentHub.Orchestration.Data.Entities.SessionEntity", "Session")
                        .WithMany("Approvals")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.SessionEntity", b =>
                {
                    b.HasOne("AgentHub.Orchestration.Data.Entities.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.SessionEventEntity", b =>
                {
                    b.HasOne("AgentHub.Orchestration.Data.Entities.SessionEntity", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentHub.Orchestration.Data.Entities.SessionEntity", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
