using System.Net.ServerSentEvents;
using System.Threading.Channels;
using AgentHub.Contracts;
using AgentHub.Orchestration.Data;
using AgentHub.Orchestration.Data.Entities;
using AgentHub.Orchestration.Events;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace AgentHub.Tests;

public class DurableEventServiceTests
{
    private static AgentHubDbContext CreateInMemoryDb(string? dbName = null)
    {
        var options = new DbContextOptionsBuilder<AgentHubDbContext>()
            .UseInMemoryDatabase(dbName ?? Guid.NewGuid().ToString())
            .Options;
        return new AgentHubDbContext(options);
    }

    private static IDbContextFactory<AgentHubDbContext> CreateFactory(string? dbName = null)
    {
        var name = dbName ?? Guid.NewGuid().ToString();
        var options = new DbContextOptionsBuilder<AgentHubDbContext>()
            .UseInMemoryDatabase(name)
            .Options;
        return new InMemoryDbContextFactory(options);
    }

    /// <summary>
    /// Simple IDbContextFactory for InMemory provider that shares the same DB name.
    /// </summary>
    private sealed class InMemoryDbContextFactory : IDbContextFactory<AgentHubDbContext>
    {
        private readonly DbContextOptions<AgentHubDbContext> _options;
        public InMemoryDbContextFactory(DbContextOptions<AgentHubDbContext> options) => _options = options;
        public AgentHubDbContext CreateDbContext() => new AgentHubDbContext(_options);
    }

    private static SessionEvent MakeEvent(string sessionId = "session-1", string data = "test data")
    {
        return new SessionEvent(sessionId, SessionEventKind.Info, DateTimeOffset.UtcNow, data);
    }

    private static async Task SeedSession(IDbContextFactory<AgentHubDbContext> factory, string sessionId = "session-1")
    {
        await using var db = factory.CreateDbContext();
        if (!await db.Sessions.AnyAsync(s => s.SessionId == sessionId))
        {
            db.Sessions.Add(new SessionEntity
            {
                SessionId = sessionId,
                OwnerUserId = "dev-user",
                State = SessionState.Running,
                CreatedUtc = DateTimeOffset.UtcNow,
                Backend = "in-memory",
                RequirementsJson = "{}"
            });
            await db.SaveChangesAsync();
        }
    }

    [Fact]
    public async Task EmitAsync_PersistsEventToDb_WithAutoGeneratedId()
    {
        // Arrange
        var dbName = Guid.NewGuid().ToString();
        var factory = CreateFactory(dbName);
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);
        var ev = MakeEvent(data: "persisted event");

        // Act
        await service.EmitAsync(ev);

        // Assert
        await using var db = factory.CreateDbContext();
        var stored = await db.Events.FirstOrDefaultAsync();
        Assert.NotNull(stored);
        Assert.True(stored.Id > 0, "Event should have auto-generated Id > 0");
        Assert.Equal("persisted event", stored.Data);
        Assert.Equal("session-1", stored.SessionId);
        Assert.Equal(SessionEventKind.Info, stored.Kind);
    }

    [Fact]
    public async Task EmitAsync_BroadcastsToSessionSubscribers()
    {
        // Arrange
        var factory = CreateFactory();
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        var ch = Channel.CreateUnbounded<SseItem<SessionEvent>>();
        var connId = Guid.NewGuid();
        subs.AddSessionSubscriber("session-1", connId, ch.Writer);

        // Act
        await service.EmitAsync(MakeEvent(data: "broadcast test"));

        // Assert
        Assert.True(ch.Reader.TryRead(out var received));
        Assert.Equal("broadcast test", received.Data.Data);
        Assert.NotNull(received.EventId);
    }

    [Fact]
    public async Task EmitAsync_BroadcastsToFleetSubscribers()
    {
        // Arrange
        var factory = CreateFactory();
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        var ch = Channel.CreateUnbounded<SseItem<SessionEvent>>();
        var connId = Guid.NewGuid();
        subs.AddFleetSubscriber(connId, ch.Writer);

        // Act
        await service.EmitAsync(MakeEvent(data: "fleet broadcast"));

        // Assert
        Assert.True(ch.Reader.TryRead(out var received));
        Assert.Equal("fleet broadcast", received.Data.Data);
    }

    [Fact]
    public async Task SubscribeSession_WithLastEventId_ReplaysEventsFromDb()
    {
        // Arrange
        var dbName = Guid.NewGuid().ToString();
        var factory = CreateFactory(dbName);
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        // Emit 3 events
        await service.EmitAsync(MakeEvent(data: "event-1"));
        await service.EmitAsync(MakeEvent(data: "event-2"));
        await service.EmitAsync(MakeEvent(data: "event-3"));

        // Get the ID of the first event to replay after it
        await using var db = factory.CreateDbContext();
        var firstEvent = await db.Events.OrderBy(e => e.Id).FirstAsync();

        // Act - subscribe with lastEventId = first event's ID (should replay events 2 and 3)
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        var replayed = new List<SseItem<SessionEvent>>();

        await foreach (var item in service.SubscribeSession("session-1", firstEvent.Id.ToString(), cts.Token))
        {
            replayed.Add(item);
            if (replayed.Count >= 2) break; // We expect 2 replayed events
        }

        // Assert
        Assert.Equal(2, replayed.Count);
        Assert.Equal("event-2", replayed[0].Data.Data);
        Assert.Equal("event-3", replayed[1].Data.Data);
    }

    [Fact]
    public async Task SubscribeSession_WithoutLastEventId_OnlyStreamsLiveEvents()
    {
        // Arrange
        var factory = CreateFactory();
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        // Emit an event BEFORE subscribing
        await service.EmitAsync(MakeEvent(data: "before-subscribe"));

        // Act - subscribe without lastEventId
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        var received = new List<SseItem<SessionEvent>>();

        // Start consuming in background
        var consumeTask = Task.Run(async () =>
        {
            await foreach (var item in service.SubscribeSession("session-1", null, cts.Token))
            {
                received.Add(item);
                if (received.Count >= 1) break;
            }
        });

        // Give the subscriber time to register
        await Task.Delay(100);

        // Emit a live event
        await service.EmitAsync(MakeEvent(data: "live-event"));

        // Wait for consumption
        await consumeTask;

        // Assert - should only get the live event, not the pre-existing one
        Assert.Single(received);
        Assert.Equal("live-event", received[0].Data.Data);
    }

    [Fact]
    public async Task SubscribeFleet_WithLastEventId_ReplaysFleetEvents()
    {
        // Arrange
        var dbName = Guid.NewGuid().ToString();
        var factory = CreateFactory(dbName);
        await SeedSession(factory, "session-a");
        await SeedSession(factory, "session-b");
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        // Emit events for different sessions
        await service.EmitAsync(MakeEvent("session-a", "event-a1"));
        await service.EmitAsync(MakeEvent("session-b", "event-b1"));
        await service.EmitAsync(MakeEvent("session-a", "event-a2"));

        // Get first event ID
        await using var db = factory.CreateDbContext();
        var firstEvent = await db.Events.OrderBy(e => e.Id).FirstAsync();

        // Act - subscribe fleet with lastEventId = first
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        var replayed = new List<SseItem<SessionEvent>>();

        await foreach (var item in service.SubscribeFleet(firstEvent.Id.ToString(), cts.Token))
        {
            replayed.Add(item);
            if (replayed.Count >= 2) break;
        }

        // Assert - should get events from both sessions
        Assert.Equal(2, replayed.Count);
        Assert.Equal("event-b1", replayed[0].Data.Data);
        Assert.Equal("event-a2", replayed[1].Data.Data);
    }

    [Fact]
    public async Task DisconnectedSubscriber_IsCleanedUp()
    {
        // Arrange
        var factory = CreateFactory();
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        // Act - start a subscription and cancel it
        using var cts = new CancellationTokenSource();
        var consumeTask = Task.Run(async () =>
        {
            try
            {
                await foreach (var _ in service.SubscribeSession("session-1", null, cts.Token))
                {
                    // Just consume
                }
            }
            catch (OperationCanceledException) { }
        });

        // Give subscriber time to register
        await Task.Delay(100);
        Assert.Equal(1, subs.GetSessionSubscriberCount("session-1"));

        // Cancel the subscription
        cts.Cancel();
        await Task.Delay(200); // Give time for cleanup

        // Assert - subscriber should be cleaned up
        Assert.Equal(0, subs.GetSessionSubscriberCount("session-1"));
    }

    [Fact]
    public async Task Events_YieldedAsSseItem_WithEventIdSetToDbId()
    {
        // Arrange
        var dbName = Guid.NewGuid().ToString();
        var factory = CreateFactory(dbName);
        await SeedSession(factory);
        var subs = new SseSubscriptionManager();
        var service = new DurableEventService(factory, subs);

        // Set up a session subscriber to capture broadcast
        var ch = Channel.CreateUnbounded<SseItem<SessionEvent>>();
        subs.AddSessionSubscriber("session-1", Guid.NewGuid(), ch.Writer);

        // Act
        await service.EmitAsync(MakeEvent(data: "check-id"));

        // Assert - get the DB-assigned ID
        await using var db = factory.CreateDbContext();
        var entity = await db.Events.FirstAsync();

        Assert.True(ch.Reader.TryRead(out var sseItem));
        Assert.Equal(entity.Id.ToString(), sseItem.EventId);
        Assert.Equal("check-id", sseItem.Data.Data);
    }
}
